CREATE TABLE EMPLOYEE(
EMPCODE CHAR(4) NOT NULL,
EMPNAME CHAR(10) NOT NULL,
EMPDESIGNATION CHAR(30) NOT NULL,
EMPDOB DATE NOT NULL,
EMPSALARY NUMERIC NOT NULL,
PRIMARY KEY(EMPCODE)
);

INSERT INTO EMPLOYEE VALUES ('e1','PRIYANKA','OFFICE ASSISTANT','1989-02-19','30000');
INSERT INTO EMPLOYEE VALUES ('e2','VIMAL','MANAGER','1993-12-08','45000');

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET EMPSALARY = '33000' WHERE EMPCODE = 'e1';

DELETE FROM EMPLOYEE WHERE EMPCODE = 'e2';
SELECT * FROM EMPLOYEE;