CREATE TABLE CLASS (
ID INT,
NAME CHAR(15)
);
INSERT INTO CLASS VALUES(1,'ABHINAV');
INSERT INTO CLASS VALUES(7,'ADAM');
SELECT * FROM CLASS;

START TRANSACTION;
INSERT INTO CLASS VALUES(31,'PARVANA');
SELECT * FROM CLASS;
SAVEPOINT A;

INSERT INTO CLASS VALUES(33,'ROHAN');
SELECT * FROM CLASS;
SAVEPOINT B;

ROLLBACK TO A;
SELECT * FROM CLASS;
COMMIT;
